# Generated by Django 3.2.4 on 2021-06-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='storage')),
            ],
        ),
    ]
