# Generated by Django 3.2.5 on 2021-07-13 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=200)),
                ('date_event', models.DateField()),
                ('user_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=200)),
                ('image_item', models.ImageField(upload_to='storage/item/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item_group', models.CharField(max_length=200)),
                ('image_item_group', models.ImageField(upload_to='storage/item_group/')),
                ('sort_priority_item_group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item_type', models.CharField(max_length=200)),
                ('image_item_type', models.ImageField(upload_to='storage/item_type/')),
                ('sort_priority_item_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_storage', models.CharField(max_length=200)),
                ('user_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_storage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_item_request', models.IntegerField()),
                ('status', models.CharField(choices=[('TD', 'ToDo'), ('IP', 'InProgress'), ('D', 'Done'), ('UD', 'UnDone'), ('C', 'Canceled')], default='TD', max_length=2)),
                ('event_item_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_item_request', to='storage.event')),
                ('item_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_request', to='storage.item')),
                ('storage_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_in', to='storage.storage')),
                ('storage_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_out', to='storage.storage')),
            ],
        ),
        migrations.CreateModel(
            name='ItemContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_container', models.IntegerField()),
                ('item_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_container', to='storage.item')),
                ('storage_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_container', to='storage.storage')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='group_item',
            field=models.ManyToManyField(related_name='group', to='storage.ItemGroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='type_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_item', to='storage.itemtype'),
        ),
    ]
