# Generated by Django 3.2.5 on 2021-07-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_itemgroup', models.CharField(max_length=200)),
                ('image_itemgroup', models.ImageField(upload_to='storage/itemgroup/')),
                ('sortpriority_itemgroup', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_itemtype', models.CharField(max_length=200)),
                ('image_itemtype', models.ImageField(upload_to='storage/itemtype/')),
                ('sortpriority_itemtype', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_storage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=200)),
                ('image_item', models.ImageField(upload_to='storage/item/')),
                ('group_item', models.ManyToManyField(related_name='group', to='storage.ItemGroup')),
                ('type_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='storage.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='storage.item')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='storage.storage')),
            ],
        ),
    ]
