# Generated by Django 3.2.5 on 2021-07-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
