# Generated by Django 3.2.5 on 2021-07-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('storage', '0003_alter_order_status_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='group_storage',
        ),
        migrations.AddField(
            model_name='storage',
            name='groups_storage',
            field=models.ManyToManyField(blank=True, related_name='groups_storage', to='auth.Group'),
        ),
    ]
