# Generated by Django 3.2.5 on 2021-07-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('storage', '0004_auto_20210725_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_order', to='auth.group'),
            preserve_default=False,
        ),
    ]
