# Generated by Django 3.2.5 on 2021-07-17 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_itemrequest_order_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='order_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.order'),
        ),
    ]
